### ISSUE TITLE
Database Projects extension: Build error on Linux (reproing on WSL)

### ISSUE THREAD

**Issue by krlmlr** [microsoft/azuredatastudio#11200]
Issue Type: <b>Bug</b>

1. Install .Net Core SDK: `apt install dotnet-sdk-3.1`
1. Configure `/usr/bin` as location for .Net Core SDK: `"sqlDatabaseProjects.netCoreSDKLocation": "/usr/bin"`
1. Create new database project: Ctrl + Shift + P, "proj new" (Database Projects: New Database Project)
1. Build the project: In "Projects" pane, right-click on `.sqlproj` file, select "Build"

Error:

```
stdout: /xxx/test/obj/Debug/test.dll : Build error SQL72025: The referenced assembly /XXX/TEST/OBJ/DEBUG/TEST.DLL is corrupt or not valid. [/xxx/test/test.sqlproj]
```

Fails on Ubuntu 18.04. Works on macOS.

Extension version: 0.1.1
Azure Data Studio version: azuredatastudio-insiders 1.20.0-insider (fd29e351990ab1306f674d1fcc9a6820cbbfcc36, 2020-07-02T05:33:26.885Z)
OS version: Linux x64 4.15.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.29GB (8.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by gavincampbell** [comment]
I can reproduce in a Fedora 32 toolbox, Data Studio commit 2d989e extension version 0.1.1

**Comment by krlmlr** [comment]
Thanks. Are you referring to 2d989e1?

I suspect this is not a problem with the extension, because `dotnet build` run from the console gives the same error. Still it will affect users of the extension. Happy to follow any pointers.

**Comment by gavincampbell** [comment]
yes, that;s the right commit. I have tried from the console too, same message. It is the extension that downloads the build-time dependencies and sets `NETCoreTargetsPath="/var/home/gavin/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.1.1/BuildDirectory"`

**Comment by simonsabin** [comment]
Looking at this I wonder if its a case issue, where the DLL name is being UPPER CASED and thus can't be found

**Comment by krlmlr** [comment]
Thanks for confirming this. It works on macOS which also has a case-insensitive file system by default.

**Comment by simonsabin** [comment]
It’s interesting that the error message has the paths in upper case, that’s what led me to believe that could be the issue

**Comment by simonsabin** [comment]
Its definitely case. Just checked and MacOS the default for the ABFS is case insensitive from 10.3 https://developer.apple.com/documentation/foundation/file_system/about_apple_file_system

**Comment by krlmlr** [comment]
I can work around by adding uppercase symlinks to the correct directories, e.g.:

```sh
sudo ln -s /home /HOME
sudo ln -s /home/username /home/USERNAME
...
```

The generated `obj/Debug/Model.xml` contains the bad path in a `"FileName"` element.

**Comment by krlmlr** [comment]
A very similar problem occurs if the project includes a post-deployment script: Can't find `/.../POSTDEPLOY.SQL`.

**Comment by udeeshagautam** [comment]
Autoclsed with PR. Reopenening to track till update.

**Comment by krlmlr** [comment]
Nice, thanks! Can you share a link to the fix in DacFx? How can I use `dotnet build` without installing Azure Data Studio (e.g. in a Docker container)?

**Comment by simonsabin** [comment]
https://www.nuget.org/packages/Microsoft.SqlServer.DACFx/

**Comment by udeeshagautam** [comment]
Build is fixed for Linux with latest insiders build (extension version 0.1.2).
For using command line build will document and share the steps soon.

**Comment by simonsabin** [comment]
Just updated to the latest bits in ADS insiders and the extension updated to 0.1.2 but I still get the error.

c:\Users\SimonSabin\source\repos\template.sql\src\TemplateProject.Db\obj\Debug\TemplateProject.Db.dll : Build error SQL72025: The referenced assembly C:\USERS\SIMONSABIN\SOURCE\REPOS\TEMPLATE.SQL\SRC\TEMPLATEPROJECT.DB\OBJ\DEBUG\TEMPLATEPROJECT.DB.DLL is corrupt or not valid. 

Creating a new empty project gives the same error

**Comment by krlmlr** [comment]
@udeeshagautam: It would be great to understand command line build and also to know the upstream repository of the source code that is responsible for the errors. Ultimately I want to run `dotnet build` in a Docker container; I'm working around by copying assemblies from Azure Database Studio into the project, there must be a better way.

**Comment by udeeshagautam** [comment]
@simonsabin as of now this is the change is made only for Linux because by default Linux is the case-sensitive file system. From the error you shared it seems like you are using Windows. However for MAC and Windows with default settings, file paths are case insensitive and hence the all caps path should not affect build. Can you please share more around if you are using any specific case sensitive setting on Windows?

**Comment by udeeshagautam** [comment]
@krlmlr sure we will document the same. Regarding the build error on linux, are you still getting the same?

**Comment by simonsabin** [comment]
We’ve been testing with wsl and thus that’s making the directories case sensitive.

Wonder why the change hasn’t been made for all?

How are you detecting linux?

Simon Sabin

________________________________

**Comment by simonsabin** [comment]
Also tried direct on wsl using pwsh core and it doesn’t work.

Simon Sabin

________________________________

**Comment by udeeshagautam** [comment]
Thanks @simonsabin for the details. Will share an update soon.

**Comment by udeeshagautam** [comment]
Hi @simonsabin, can you please try to use the latest nsiders build for ADS and verify if the issue with caps in dll pasth is fixed for your scenario. You should only need the insiders update for ADS and same extension version (0.1.2). Please let us know if you still see the issue. Thanks for your help!

**Comment by udeeshagautam** [comment]
Hi @simonsabin, @krlmlr, this is fixed in insider builds for ADS. Can you please let us know if you still see this issue.

**Comment by simonsabin** [comment]
Will check this week.

**Comment by udeeshagautam** [comment]
Closing this issue since this has been fixed. Please let us know if you still see this issue.
