### ISSUE TITLE
Remove unused attachments from cell metadata

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#15635]
Images pasted into cells are added to cell metadata as attachments and are rendered as such in markdown code. If the user deletes the image, it deletes it from the code but it doesn't remove the attachment from the metadata. 

Provide a way to remove the unused attachments from polluting the metadata.

**Comment by MsSQLGirl** [comment]
@MaddyDev  / @chlafreniere - FYI:  The problem still persisted.  I tested this on Insiders, i.e.
Version: 1.31.0-insider (user setup)
Commit: e8ba89750bae05438d729302c62f092ce3e5f01c
Date: 2021-07-02T05:29:28.141Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by chlafreniere** [comment]
@MsSQLGirl ack

**Comment by MsSQLGirl** [comment]
@chlafreniere  

Also, documenting an issue that was related to this thread. It is fixed in 1.31.0 Insiders though. Worthwhile adding this as a test case:

In the stable version 1.30.0, as detailed at the end of this comment, we noticed that if a user has an attachment image in a text cell, the next time the user makes an edit to the text cell, the existing attachment image is duplicated (and I think the reference is changed also). One of the notebook that I created using v1.30.0 managed to explode to 3MB. After manually cleaning it up, it became 320KB - it duplicated ~20x. 
Version: 1.30.0 (user setup)
Commit: 59c4b8e90cf2d3a24bed72623197f10f8d090fdc
Date: 2021-06-16T19:04:08.858Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

Mentioning it here only as a FYI and make sure that the test case covers for this experience, i.e. editing existing cell with existing attachment image.

**Comment by Charles-Gagnon** [comment]
@MsSQLGirl Could you please list the exact steps you're taking that result in the issue still occurring? I just tested it myself on insiders and it seems to work as expected.

**Comment by MsSQLGirl** [comment]
@Charles-Gagnon 
The steps to repro:
1. Create a text cell using WYSIWYG mode. Type a few lines (with words / numbers etc)
2. Copy and paste an image between the ines. This should invoke the attachment image. 
3. Exit out of text cell. Save. 
4. Edit the cell that you have just created. Above the image, remove or add a new line of words / numbers etc.
5. Save the file.
6. Go to notepad++ and open the notebook file and you'll see the json file will create a duplicate image.

This is reproable in  1.30.0. It seems to be solved in Insiders, but I would recommend to include this as part of a test case in Insiders.

A couple of users from live site have reported that they have experienced this behavior which cause the notebook to be bloated unnecessarily therefore causing ADS to be sluggish.

**Comment by Charles-Gagnon** [comment]
That sounds like a different issue than what this one is describing, which is about attachment data not being removed when the image was deleted.

If that's the case could you please open a new issue for that so we can track it separately?

**Comment by MsSQLGirl** [comment]
New tracking here: https://github.com/microsoft/azuredatastudio/issues/16004

**Comment by Charles-Gagnon** [comment]
Closing since this one should be fixed
