### ISSUE TITLE
Formatting not kept on copy+paste

### ISSUE THREAD

**Issue by fsmythe** [microsoft/azuredatastudio#16915]
Issue Type: <b>Bug</b>

Format of field not kept when copying and pasting into other applications, ie Visual Studio, Excel, Sublime text.

How field actually looks (hovering over field in results pane):
![How field actually looks](https://user-images.githubusercontent.com/1161466/131105496-eb532d08-d1d4-4ca6-bcc1-a5fb98aebcdf.PNG)

How it looks after pasting into IDE:
![Result in IDE](https://user-images.githubusercontent.com/1161466/131105500-00576374-4731-4677-8342-651b5473aa72.PNG)

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@fsmythe I just tried this with long html content and unchecking the configuration worked for me. have you tried to reopen the query editor after making the configuration change?

![image](https://user-images.githubusercontent.com/13777222/132050863-4cc911fc-ef1f-4753-9bea-608475deee0e.png)

**Comment by alanrenmsft** [comment]
The issue has been fixed.

**Comment by fsmythe** [comment]
Hi, sorry to bring up an old thread/issue but still persists. See more detailed screenshots below. Setting was unticked then Azure Data Studio completely restarted. No effect.

Hover over field in azure data studio, note the carriage return symbols:
![azuredatastudio_Cga7147EOv](https://github.com/microsoft/azuredatastudio/assets/1161466/22c6ddf2-0be2-425e-9917-a731cb4a09ae)

After copy and pasting into visual studio code:
![Code_Gss5gYH7tH](https://github.com/microsoft/azuredatastudio/assets/1161466/1973d35d-231c-4853-9745-0be437544948)

Showing setting is unticked (tried ticked too no difference)
![azuredatastudio_H0OngPIKBb](https://github.com/microsoft/azuredatastudio/assets/1161466/96b1cf63-7c61-497a-9651-83d7afda8406)

Same field copy and pasted from SQL Management Studio 19 (no issues):
![Ssms_FVJlGU0HBN](https://github.com/microsoft/azuredatastudio/assets/1161466/44001246-3089-4f6d-8480-7138c260bac4)

Let me know if you need anything else.

**Comment by fsmythe** [comment]
> The issue has been fixed.

Issue not fixed for me, see above, should I open a new issue or can you re-open this one for me? Thanks
