### ISSUE TITLE
Connection explorer is unable to retrieve tables' list

### ISSUE THREAD

**Issue by ferran-b** [microsoft/azuredatastudio#19166]
Issue Type: <b>Bug</b>

Open a connection
Navigate on the left pane to the connections list
Expand the connection
Expand the "Tables" folder
Tmeout message appears

This happens in Mac and Windows machines on Azure Data Studio 1.36

Azure Data Studio version: azuredatastudio 1.36.0 (0704471e6b4a79f0c2c2425b22dc6bee60a1c2a8, 2022-04-19T18:21:59.017Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0

</details>

**Comment by kburtram** [comment]
@lewis-sanchez could you please investigate and try to repro?  There is additional details in the duplicate bugs as well.  Thanks!

**Comment by Charles-Gagnon** [comment]
I'm seeing this error in the logs, unsure if it's actually related and/or new at all but probably worth looking into

```
22-04-21 9:58:55.6764562 pid:20264 tid:12 sqltools Error: 0 : Microsoft.SqlServer.Management.Smo.UnknownPropertyException: Processors: unknown property.
   at Microsoft.SqlServer.Management.Smo.SqlPropertyMetadataProvider.PropertyNameToIDLookupWithException(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName)
   at Microsoft.SqlServer.Management.Smo.Server.get_Processors()
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableConnectionHelper.GetServerCpuAndMemoryInfo(IDbConnection connection) in D:\a\_work\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableConnectionHelper.cs:line 799
``

**Comment by kburtram** [comment]
It appears that a change to support Graph table icons in Object Explorer introduced a bunch of new SMO metadata queries related to stretchdb for each table.  All these extra metadata queries are likely causing these timeouts.  We're working on a hotfix to push ASAP to address.  The new queries on table expansion should look like `exec sp_executesql N'CREATE TABLE #tmp_extended_remote_data_archive_tables...`.

**Comment by Chewieez** [comment]
Here are those 2 logs from my Macbook Air M1

[main.log.zip](https://github.com/microsoft/azuredatastudio/files/8534322/main.log.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/8534329/console.log)

**Comment by Charles-Gagnon** [comment]
@Chewieez What server are you connecting to? And could you see if reverting back to the previous release fixes the issue?

(links here : https://github.com/microsoft/azuredatastudio/releases/tag/1.35.1)

**Comment by Charles-Gagnon** [comment]
Sorry, to be clear I meant the type of server and version you're connecting to 

(run `SELECT @@VERSION` and paste the contents)

**Comment by Chewieez** [comment]
> Sorry, to be clear I meant the type of server and version you're connecting to
> 
> (run `SELECT @@VERSION` and paste the contents)

Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)  	Jan 12 2022 22:30:08  	Copyright (C) 2019 Microsoft Corporation 	Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

Yes, reverting to the previous release fixes the issue.

**Comment by kburtram** [comment]
@Chewieez we're preparing a Hotfix release for this issue.  If you have time, could you please see if this release candidate validation build resolves the issue in your environment https://azuredatastudiobuilds.blob.core.windows.net/test/1.36.1/azuredatastudio-win32-1.36.1-revert_oe_icon.zip?  It contains a revert for the Object Explorer change that is introducing extra metadata queries.  Thanks!

**Comment by Chewieez** [comment]
Hi @kburtram, could you possibly provide a Mac OS version of the RC? I use a M1 Macbook Air. Thanks! I'd be happy to install and check it out.

**Comment by kburtram** [comment]
@Chewieez sure, here's the macos build https://azuredatastudiobuilds.blob.core.windows.net/test/1.36.1/azuredatastudio-darwin-1.36.1-revert_oe_icon.zip.  We're planning to push the release tomorrow assuming no verification issues in the meantime, so the build may be published by the time you're ready to test.  Either way, it would be great to get confirmation when the issue is resolved.  Thanks!

**Comment by andy-fenn** [comment]
Based on comments above I have done some more testing this morning.
This issue does not occur when connecting to our Azure SQL DBs, it only seems to happen when connecting to our Azure Synapse SQL Pools.

**Comment by koch-mi** [comment]
Hi all,
same issue when connecting to SQL Managed Instance Databases. I think it depends on the number of tables in that database. We have a test database with only 3 tables and here it works fine. Other databases on SQL Managed Instance and dedicated SQL Pool with 100+ tables show the same error.

**Comment by koch-mi** [comment]
@kburtram the issue doesn't show up on the RC 1.36.1 win32. I'm able to browse the tables in SQL Managed Instance database and also in dedicated SQL Pool.

**Comment by Chewieez** [comment]
> @Chewieez sure, here's the macos build https://azuredatastudiobuilds.blob.core.windows.net/test/1.36.1/azuredatastudio-darwin-1.36.1-revert_oe_icon.zip. We're planning to push the release tomorrow assuming no verification issues in the meantime, so the build may be published by the time you're ready to test. Either way, it would be great to get confirmation when the issue is resolved. Thanks!

Thanks for the Mac OS link. 

The RC hotfix works on my Macbook. My Tables folder opens and populates almost instantaneously now. 

For a datapoint, we currently have 347 tables in this SQL server database.

**Comment by Charles-Gagnon** [comment]
We've just released a hotfix (v1.36.1) that has the fix for this issue, please let us know if you see any further issues after updating!

**Comment by andy-fenn** [comment]
v1.36.1 is working for us. 
Thank you so much for fixing this so quickly.

**Comment by BillGuenthner** [comment]
This is very much still an issue when using Azure Data Studio on MacOS and attempting to list databases in Azure SQL. I have 200+ database and cannot use Azure Data Studio because of this limitation.

Version: 1.39.1
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:12:48.559Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.6.0

**Comment by chris-larsen** [comment]
Preview release seems to reintroduce this issue on MacOS ARM build.

**Comment by cnkeats** [comment]
I am also having this issue on MacOS when listing objects in Azure SQL databases

ADS Version 1.39.1
MacOS Monterey 12.6

**Comment by shreymehtaqrg** [comment]
Can we reopen this ticket? We are also facing this issue. 

Version: 1.40.1 (user setup)
Commit: 3a32679ab590c1023ab4de6f191769e7e127d25b
Date: 2022-11-22T18:30:25.850Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by peter-dolkens** [comment]
CC @Charles-Gagnon this is still an issue it seems.

Just downloaded 1.40.2 and can't expand an Azure SQL instance with 8 databases in it on my M2 Macbook Air

**Comment by peter-dolkens** [comment]
Can confirm - this is working much better in the insiders build 1.42

```
Version: 1.42.0-insider
Commit: e2a7767b53c82ea8f045c57f01e7010c37094083
Date: 2023-01-23T06:52:02.899Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
```

CC @shreymehtaqrg @cnkeats @chris-larsen @BillGuenthner

**Comment by Trymzet** [comment]
Broken again (or still) on 1.44.1 on Windows 11.
