### ISSUE TITLE
Unable to list views

### ISSUE THREAD

**Issue by TimoBahama** [microsoft/azuredatastudio#21171]
I cant list my views anymore. Table listing is ok.

Version: 1.39.1
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:12:48.559Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.7.0

<img width="1395" alt="Screenshot 2022-11-09 at 9 55 43 AM" src="https://user-images.githubusercontent.com/35799097/200726298-0eb8ed34-16d9-4c26-b229-8713a53c9185.png">

**Comment by lewis-sanchez** [comment]
HI @TimoBahama, I was unable to reproduce this for a local SQL DB and an Azure SQL DB. Would you be able to share any warnings/errors you see in the dev tools console.

You can open the dev tools console like this, if you aren't sure on how to do that:
![image](https://user-images.githubusercontent.com/87730006/201741467-90592f5e-b6db-46a2-9e32-1387560e5f37.png)

**Comment by TimoBahama** [comment]
[console.log](https://github.com/microsoft/azuredatastudio/files/10010307/console.log)
[logs.zip](https://github.com/microsoft/azuredatastudio/files/10010308/logs.zip)

Please kindly find the requested elements attached

**Comment by aasimkhan30** [comment]
@TimoBahama , we have fixed this issue with the latest release 1.40.1. Can you please update your ADS and give it a try.

**Comment by TimoBahama** [comment]
Hi !

So happy to have feedback from you.
I did the last update a few days ago, unfortunately I still have the
problem with the views display.



Warmly,

Timothée Lenglart

+1 (702) 706 1613 <http://voice.google.com/calls?a=nc,%2B17027061613>


Le mar. 13 déc. 2022 à 23:37, Aasim Khan ***@***.***> a
écrit :

**Comment by lewis-sanchez** [comment]
@TimoBahama, do you still experience this issue in insider version 1.41.0?

**Comment by TimoBahama** [comment]
yes still the issue:

[image: Screenshot 2022-12-21 at 1.34.40 PM.png]



Warmly,

Timothée Lenglart

+1 (702) 706 1613 <http://voice.google.com/calls?a=nc,%2B17027061613>


Le mer. 21 déc. 2022 à 06:28, Lewis Sanchez ***@***.***> a
écrit :

**Comment by cheenamalhotra** [comment]
The root cause looks similar to https://github.com/microsoft/azuredatastudio/issues/21541 though..

**Comment by TimoBahama** [comment]
Hi, yes it seems to be exactly the same.



Warmly,

Timothée Lenglart

+1 (702) 706 1613 <http://voice.google.com/calls?a=nc,%2B17027061613>


Le mar. 10 janv. 2023 à 03:07, Cheena Malhotra ***@***.***> a
écrit :

**Comment by TimoBahama** [comment]
Hi Guys,

Everything works fine since the last update now.
You are the best.



Warmly,

Timothée Lenglart

+1 (702) 706 1613 <http://voice.google.com/calls?a=nc,%2B17027061613>
