### ISSUE TITLE
OE server nodes not expanding

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#21578]
![OE_insider](https://user-images.githubusercontent.com/21186993/211961964-16b479b1-68d2-4d64-b26f-1223dfa0eafe.gif)

There's a chance that if a user clicks / expands a saved SQL Server, the server will connect but not expand (green but spinning). The user will have to click on a **second** server for the **first** server to successfully expand. This should be easily reproducible especially with multiple Azure SQL DBs. 

This behavior is very likely caused by this commit https://github.com/microsoft/azuredatastudio/commit/e2327c393ad2a4947038b975a52d17200be49d6c, I've tried to revert this commit with latest main and the issue is gone. I haven't figured out what actual part of the change has caused this issue, maybe @corivera could take a closer look at the files removed/modified. Worst-case scenario we can just revert this whole commit given the priority and time left before the code complete.

```
Version: 1.41.0-insider (user setup)
Commit: a400ff2f43be2e75fbf9845ca8b545380ca4813a
Date: 2023-01-11T06:28:12.910Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
```

cc @alanrenmsft @kburtram @corivera @Charles-Gagnon

**Comment by caohai** [comment]
> Do you have more information? Any errors in the console or STS logs?

There's no error in ADS console or STS log.
![Screen Shot 2023-01-12 at 10 06 52](https://user-images.githubusercontent.com/21186993/212145487-459888ee-9812-4ca1-a44a-e8c5a7373972.png)
From STS log I can see `objectexplorer/expandCompleted` event but the OE server node just won't expand.

This should be easily reproducible with a few Azure SQL DBs using latest insider build / dev build.

**Comment by alanrenmsft** [comment]
@caohai are you working on this?

**Comment by caohai** [comment]
> @caohai are you working on this?

@alanrenmsft Not any more, I spent a few hours attempting to revert some files in `extensions/mssql` yesterday but was not able to do it in a clean way. Some code appears to be coupled and I'm not sure if some modified code is only for BDC.

I've pinged Cory for this and he's taking a look. Worst case we can revert the whole commit.

**Comment by corivera** [comment]
Reverting the entire commit might not be a good idea, since we removed BDC stuff from tools service too. So we might start seeing different errors.

**Comment by alanrenmsft** [comment]
@corivera how about only removing the entry points for BDC for now? could you please take care of this issue?

**Comment by corivera** [comment]
Looking into it

**Comment by cheenamalhotra** [comment]
Just looking around the code, I found something interesting going on in OE session handlers.. 
This section declares handlers for OE activities, and it seems to be mixing both `ObjectExplorerProvider` and `ObjectExplorerNodeProvider` providers..
https://github.com/microsoft/azuredatastudio/blob/fb6e221fff15c1d3dba6c0a1155c0a3fe06bf986/src/sql/workbench/api/common/extHostDataProtocol.ts#L474-L500

- Do we need both types?
- `ObjectExplorerNodeProvider` is what was implemented in mssql extension that got removed in that commit.. as it seems that was applicable to Cluster sessions only or was also shared for non-cluster OE node provider handler activity?

`handleSessionOpen` and `handleSessionClose` seem to be missing handlers now, that were handled by `MssqlObjectExplorerNodeProvider` as it got removed in commit https://github.com/microsoft/azuredatastudio/commit/e2327c393ad2a4947038b975a52d17200be49d6c.

We could either merge these 2 types or need to bring back implementation of `ObjectExplorerNodeProvider`.

**Comment by Charles-Gagnon** [comment]
Node Providers should be optional - if I'm remembering this correctly, they're used as a way for extensions to contribute nodes to a tree originally provided by a different extension. (In this case BDC used to live in a separate extension, so it allowed that extension to add the HDFS folders to the MSSQL connection trees provided by the MSSQL extension. 

@kburtram @alanrenmsft Does that sound correct?

So a node provider not existing should just be a no-op (all nodes are provided by the original extension), and looking through 
https://github.com/Microsoft/azuredatastudio/blob/8c8a7859a02e8907af183f60a6478895123a5cdc/src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts I'm seeing that being the case.

Worth keeping in mind though in case something was missed, or some functionality expected that node provider to exist.

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra @caohai @corivera If you all are able to repro this consistently could you turn on the language server logging I'm adding here to : 

1. Make absolutely sure we're getting the expandCompleted message on the extension side
2. That the parameters being sent look correct (expected nodes/etc.)

If that all looks good then we'll want to start looking at adding more debug logging along the path it takes to call objectExplorerService.onNodeExpanded to make sure nothing is getting broken along the way there either.

**Comment by Charles-Gagnon** [comment]
Further information on what's happening here : 

The root issue looks to because objectExplorer.createNewService is being called multiple times. So what's happening when this breaks is : 

1. It's called first when the the node is clicked and the session is created. This adds it to the this._sessions map (with an empty node array)
2. Then expandOrRefreshNode is called for the root node, which adds it to the nodes map in the saved session
3. Now the second call to createSession comes in. This again resets the session in the map, which also wipes out the nodes map
4. Eventually the expand request comes back and onNodeExpanded is called, but because the map was reset it can't find the node and so fails (which means it doesn't trigger the expandEmitter event and thus it gets stuck)

When it works correctly you will still see two createSession calls but they happen like this : 

1. It's called first when the the node is clicked and the session is created. This adds it to the this._sessions map (with an empty node array)
2. Next the second call to createSession comes in. This again resets the session in the map, which doesn't change anything since it was just reset
3. Now the expandOrRefreshNode is called for the root node, which adds it to the nodes map in the saved session
4. Eventually the expand request comes back and onNodeExpanded is called, and it works as expected since the node is still in the map

If we break at createSession we see that they both come from TreeSelectionHandler.onTreeSelect, but one is for the mouse event path and the other is for the "other" path. 

The first one makes sense, that's the actual click the user did on the tree node itself. The second one is a side effect of how the tree is written. Whenever it recieves an "addConnectionProfile" event from connectionManagementService then it completely refreshes the tree, redrawing everything and [re-selecting the currently selected item](https://github.com/Microsoft/azuredatastudio/blob/8c8a7859a02e8907af183f60a6478895123a5cdc/src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts#L140). This selection is what then triggers the onTreeSelect call, which then triggers the second createSession. 

So for fixing this it seems like the best place to start is to see about making it so we only call createSession when we actually want to create a new session. Or at least know when it comes from an existing session and return that instead.

**Comment by Charles-Gagnon** [comment]
In addition - bringing the BDC code back "fixes" this by just making it must less likely that the race condition above is hit. 

When a session is created we loop through all the registered nodeProviders and [call handleSessionOpen](https://github.com/Microsoft/azuredatastudio/blob/8c8a7859a02e8907af183f60a6478895123a5cdc/src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts#L286) for them, waiting until they all return.

This extra back and forth (which goes over the JSON RPC layer) then adds enough extra time so that the second createSession event comes in and resets the session in the internal map. Eventually the handleSessionOpen calls finish, and only then does it move on to the expandOrRefreshNode call which actually adds the node.

So by having a node provider registered it just happened to be enough to get around the race condition, at least most of the time. 

(note this doesn't seem to have anything to do with the expandNode calls of the Node Provider themselves. Those aren't called until after we get to expandOrRefreshNode in the OE service, which is well past the point that the actual problem of overwriting the nodes map occurs)

**Comment by caohai** [comment]
Fixed in Jan release branch. I'll move this issue to Mar milestone for future followups.

**Comment by alanrenmsft** [comment]
@aasimkhan30 assigning to you now.

**Comment by cheenamalhotra** [comment]
@aasimkhan30 FYI, this issue is not completely fixed, I'm not sure how frequently this would occur, but I believe it's still possible that users may experience it. I was able to reproduce this today in insiders build:

Version: 1.42.0-insider (user setup)
Commit: 93f5581bc7dbe7655c4df207aaa2d2c0b1b76135
Date: 2023-02-13T22:14:30.999Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

![OE_Stuck](https://user-images.githubusercontent.com/13396919/218865328-c3ecc3ea-da21-4bba-8f19-8b7670feb0a7.gif)

It also happened with localhost instance for me before (but I didn't record), so it doesn't seem server specific.

**Comment by aasimkhan30** [comment]
Fixed with #21954
