### ISSUE TITLE
Error: Failed to expand node

### ISSUE THREAD

**Issue by tushar-hatwar** [microsoft/azuredatastudio#21691]
Issue Type: <b>Bug</b>

While expanding the Database option the Error window opens up with the Dialog  - Error: Failed to expand node

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.35GB (9.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by alanrenmsft** [comment]
@cheenamalhotra is this the thing that got fixed last week? could you please resolve this issue?

**Comment by cheenamalhotra** [comment]
Hi @alanrenmsft 
This is likely related to expired access token, and possibly fixed with https://github.com/microsoft/azuredatastudio/pull/21308

@tushar-hatwar 
To confirm, can you please gather logs and paste exception captured in MSSQL log when this error occurs?

**Comment by kburtram** [comment]
Closing based on the previous comments.  Please let us know if you're still impacted by this issue.

**Comment by mvarie** [comment]
Still happening when connecting to a MSSQL instance, trying to expand Tables folder under a Database:

```
Error: Failed to expand node
Node expansion timed out for node SERVERNAME/Databases/DATABASENAME/Tables for providers MSSQL
```

.. when connected to an instance with this SQL Server version:

```
Microsoft SQL Server 2017 (RTM-GDR) (KB5021127) - 14.0.2047.8 (X64)  	Jan 25 2023 08:29:55  	Copyright (C) 2017 Microsoft Corporation 	Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

.. however, no errors when trying to do the same with this version of SQL Server:

```
Microsoft SQL Server 2005 - 9.00.4035.00 (Intel X86)  	Nov 24 2008 13:01:59  	Copyright (c) 1988-2005 Microsoft Corporation 	Standard Edition on Windows NT 5.2 (Build 3790: Service Pack 2) 
```

Installed ADS version:

```
Azure Data Studio
Version: 1.42.0
Commit: 22f384e569bc90d8b3231cc8c8cff99ea16c5052
Date: 2023-03-17T18:00:05.633Z (5 days ago)
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.3.0
```

**renderer3.log** (sensitive info replaced by placeholders):

```
[2023-03-23 10:33:13.678] [renderer3] [warning] Settings pattern "debug.*" doesn't match any settings
[2023-03-23 10:33:13.678] [renderer3] [warning] Settings pattern "launch" doesn't match any settings
[2023-03-23 10:33:13.678] [renderer3] [warning] Settings pattern "audioCues.*" doesn't match any settings
[2023-03-23 10:33:13.679] [renderer3] [warning] Settings pattern "notebook.*" doesn't match any settings
[2023-03-23 10:33:13.679] [renderer3] [warning] Settings pattern "tableDesigner.*" doesn't match any settings
[2023-03-23 10:33:13.679] [renderer3] [warning] SettingsEditor2: Settings not included in settingsLayout.ts: sql.query.shortcut1, sql.query.shortcut2, sql.query.shortcut3, sql.query.shortcut4, sql.query.shortcut5, sql.query.shortcut6, sql.query.shortcut7, sql.query.shortcut8, sql.query.shortcut9, notebookExplorerSearch.actionsPosition, notebookExplorerSearch.collapseResults, notebookExplorerSearch.exclude, notebookExplorerSearch.followSymlinks, notebookExplorerSearch.globalFindClipboard, notebookExplorerSearch.location, notebookExplorerSearch.maintainFileSearchCache, notebookExplorerSearch.quickOpen.history.filterSortOrder, notebookExplorerSearch.quickOpen.includeHistory, notebookExplorerSearch.quickOpen.includeSymbols, notebookExplorerSearch.searchEditor.doubleClickBehaviour, notebookExplorerSearch.searchOnType, notebookExplorerSearch.searchOnTypeDebouncePeriod, notebookExplorerSearch.seedOnFocus, notebookExplorerSearch.seedWithNearestWord, notebookExplorerSearch.showLineNumbers, notebookExplorerSearch.smartCase, notebookExplorerSearch.sortOrder, notebookExplorerSearch.useGlobalIgnoreFiles, notebookExplorerSearch.useIgnoreFiles, notebookExplorerSearch.usePCRE2, notebookExplorerSearch.useReplacePreview, notebookExplorerSearch.useRipgrep, serverTree.nodeExpansionTimeout, serverTree.useAsyncServerTree, resultsGrid.autoSizeColumns, resultsGrid.cellPadding, resultsGrid.fontFamily, resultsGrid.fontSize, resultsGrid.fontWeight, resultsGrid.letterSpacing, resultsGrid.maxColumnWidth, resultsGrid.rowHeight, resultsGrid.showJsonAsLink, sql.defaultAuthenticationType, sql.defaultEngine, sql.maxRecentConnections, notebookViews.enabled
[2023-03-23 10:33:16.587] [renderer3] [warning] Settings pattern "debug.*" doesn't match any settings
[2023-03-23 10:33:16.587] [renderer3] [warning] Settings pattern "launch" doesn't match any settings
[2023-03-23 10:33:16.588] [renderer3] [warning] Settings pattern "audioCues.*" doesn't match any settings
[2023-03-23 10:33:16.588] [renderer3] [warning] Settings pattern "notebook.*" doesn't match any settings
[2023-03-23 10:33:16.588] [renderer3] [warning] Settings pattern "tableDesigner.*" doesn't match any settings
[2023-03-23 10:33:16.641] [renderer3] [error] An unknown error occurred. Please consult the log for more details.
[2023-03-23 10:33:17.254] [renderer3] [warning] Settings pattern "debug.*" doesn't match any settings
[2023-03-23 10:33:17.258] [renderer3] [warning] Settings pattern "launch" doesn't match any settings
[2023-03-23 10:33:17.258] [renderer3] [warning] Settings pattern "audioCues.*" doesn't match any settings
[2023-03-23 10:33:17.258] [renderer3] [warning] Settings pattern "notebook.*" doesn't match any settings
[2023-03-23 10:33:17.259] [renderer3] [warning] Settings pattern "tableDesigner.*" doesn't match any settings
[2023-03-23 10:33:35.544] [renderer3] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:192.168.0.1|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:33:35.545] [renderer3] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:192.168.0.1|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:33:35.545] [renderer3] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:192.168.0.1|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:33:35.871] [renderer3] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:192.168.0.1|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:34:28.149] [renderer3] [warning] 192.168.0.1_master_user.user_SqlLogin_180e6dd7-23af-4c9e-99cf-6d08cf072400: Node expansion timed out for node 192.168.0.1/Databases/DATABASENAME/Tables for providers MSSQL
[2023-03-23 10:34:28.212] [renderer3] [error] Object Explorer task didn't complete within 45 seconds.
[2023-03-23 10:34:28.212] [renderer3] [warning] Cannot find node status for session: 192.168.0.1_master_user.user_SqlLogin_180e6dd7-23af-4c9e-99cf-6d08cf072400 and node path: 192.168.0.1/Databases/DATABASENAME/Tables
[2023-03-23 10:37:13.301] [renderer3] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:13.302] [renderer3] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:13.302] [renderer3] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:18.414] [renderer3] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:18.596] [renderer3] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:18.596] [renderer3] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:18.596] [renderer3] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:22.488] [renderer3] [error] Failed to create Object Explorer session
[2023-03-23 10:37:23.756] [renderer3] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|databaseDisplayName:master|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:23.757] [renderer3] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|databaseDisplayName:master|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:37:23.757] [renderer3] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:SERVERNAME|user:user.user|databaseDisplayName:master|group:180e6dd7-23af-4c9e-99cf-6d08cf072400
[2023-03-23 10:38:32.048] [renderer3] [warning] SERVERNAME_master_user.user_SqlLogin_180e6dd7-23af-4c9e-99cf-6d08cf072400: Node expansion timed out for node SERVERNAME/Databases/DATABASENAME/Tables for providers MSSQL
[2023-03-23 10:38:32.079] [renderer3] [error] Object Explorer task didn't complete within 45 seconds.
[2023-03-23 10:38:32.080] [renderer3] [warning] Cannot find node status for session: SERVERNAME_master_user.user_SqlLogin_180e6dd7-23af-4c9e-99cf-6d08cf072400 and node path: SERVERNAME/Databases/DATABASENAME/Tables
```

**telemetry.log**

```
[2023-03-23 10:33:14.003] [fdae98f3-8971-4bbc-8b17-f6038f94d971] [info] Below are logs for every telemetry event sent from Azure Data Studio once the log level is set to trace.
[2023-03-23 10:33:14.003] [fdae98f3-8971-4bbc-8b17-f6038f94d971] [info] ===========================================================
```

**sqltools.log**

```
23-03-23 10:43:43.1651160 pid:94299 tid:11 sqltools Error: 0 : Failed getting smo objects. parent:192.168.0.1/Databases/DATABASENAME/Tables querier: Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier error:An exception occurred while executing a Transact-SQL statement or batch. inner:Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. stacktrace:   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteReader(String sqlCommand, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType resultType, StringCollection sql, Object connectionInfo, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.GetData(EnumResult erParent)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 369
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 153
23-03-23 10:43:43.1659370 pid:94299 tid:11 sqltools Error: 0 : Failed expanding oe children. parent:192.168.0.1/Databases/DATABASENAME/Tables error:An exception occurred while executing a Transact-SQL statement or batch. inner:Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. stacktrace:   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteReader(String sqlCommand, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType resultType, StringCollection sql, Object connectionInfo, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.GetData(EnumResult erParent)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 369
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 153
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(TreeNode parent, Boolean refresh, String name, Boolean includeSystemObjects, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 44
23-03-23 10:43:43.1663890 pid:94299 tid:11 sqltools Error: 0 : Failed populating oe children. error:An exception occurred while executing a Transact-SQL statement or batch. inner:Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. stacktrace:   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteReader(String sqlCommand, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType resultType, StringCollection sql, Object connectionInfo, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.GetData(EnumResult erParent)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 369
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 153
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(TreeNode parent, Boolean refresh, String name, Boolean includeSystemObjects, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 44
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.PopulateChildren(Boolean refresh, String name, CancellationToken cancellationToken, String accessToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 355
23-03-23 10:43:43.1703050 pid:94299 tid:11 sqltools Verbose: 0 : eventTID:6517923 TdsParserStateObjectManaged.WritePacket | Info | Session Id b5327e5f-63d7-4a00-b5db-ec66d5e95454, SendAsync Result 0
23-03-23 10:43:43.1710580 pid:94299 tid:11 sqltools Verbose: 0 : eventTID:6517923 TdsParserStateObjectManaged.ReadSyncOverAsync | Info | State Object Id 4, Session Id b5327e5f-63d7-4a00-b5db-ec66d5e95454
23-03-23 10:43:43.1710980 pid:94299 tid:11 sqltools Verbose: 0 : eventTID:6517923 TdsParserStateObjectManaged.ReleasePacket | Info | State Object Id 4, Session Id b5327e5f-63d7-4a00-b5db-ec66d5e95454, Packet DataLeft 197
23-03-23 10:43:43.1711590 pid:94299 tid:11 sqltools Verbose: 0 : eventTID:6517923 TdsParserStateObject.DecrementOpenResultCount | INFO | State Object Id 4, Processing Attention.
23-03-23 10:43:43.1712000 pid:94299 tid:11 sqltools Verbose: 0 : eventTID:6517923 SqlConnection.OnInfoMessage | API | Info | Object Id 4, Message 'Changed database context to 'master'.'
23-03-23 10:43:43.1714490 pid:94299 tid:18 sqltools Verbose: 0 : Done with binding operation for 192.168.0.1/Databases/DATABASENAME/Tables
23-03-23 10:43:43.1716250 pid:94299 tid:12 sqltools Verbose: 0 : OE expand canceled
23-03-23 10:47:47.0407960 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.ReadSyncOverAsync | Info | State Object Id 19, Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0
23-03-23 10:47:47.0412950 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 SqlError.ctor | ERR | Info Number -2, Error State 0, Error Class 11, Error Message 'Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.', Procedure '', Line Number 0
23-03-23 10:47:47.0413960 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.CreateAndSetAttentionPacket | Info | State Object Id 19, Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0
23-03-23 10:47:47.0416530 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.WritePacket | Info | Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0, SendAsync Result 0
23-03-23 10:47:47.0416830 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObject.SendAttention | Info | State Object Id 19, Sent Attention.
23-03-23 10:47:47.0417100 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObject.SendAttention | Info | State Object Id 19, Attention sent to the server.
23-03-23 10:47:47.0428330 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.ReadSyncOverAsync | Info | State Object Id 19, Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0
23-03-23 10:47:47.0429050 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.ReleasePacket | Info | State Object Id 19, Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0, Packet DataLeft 310
23-03-23 10:47:47.0433730 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObject.DecrementOpenResultCount | INFO | State Object Id 19, Processing Attention.
23-03-23 10:47:47.0464200 pid:94299 tid:27 sqltools Error: 0 : Failed getting smo objects. parent:SERVERNAME/Databases/DATABASENAME/Tables querier: Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier error:An exception occurred while executing a Transact-SQL statement or batch. inner:Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. stacktrace:   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 369
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 153
23-03-23 10:47:47.0469290 pid:94299 tid:27 sqltools Error: 0 : Failed expanding oe children. parent:SERVERNAME/Databases/DATABASENAME/Tables error:An exception occurred while executing a Transact-SQL statement or batch. inner:Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. stacktrace:   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 369
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 153
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(TreeNode parent, Boolean refresh, String name, Boolean includeSystemObjects, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 44
23-03-23 10:47:47.0472430 pid:94299 tid:27 sqltools Error: 0 : Failed populating oe children. error:An exception occurred while executing a Transact-SQL statement or batch. inner:Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. stacktrace:   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlTableQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 369
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 153
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(TreeNode parent, Boolean refresh, String name, Boolean includeSystemObjects, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 44
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.PopulateChildren(Boolean refresh, String name, CancellationToken cancellationToken, String accessToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 355
23-03-23 10:47:47.0479850 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.WritePacket | Info | Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0, SendAsync Result 0
23-03-23 10:47:47.0486910 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.ReadSyncOverAsync | Info | State Object Id 19, Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0
23-03-23 10:47:47.0487280 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObjectManaged.ReleasePacket | Info | State Object Id 19, Session Id 60d9af4d-f6da-4f9e-9ce5-fc0798906fd0, Packet DataLeft 197
23-03-23 10:47:47.0487980 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 TdsParserStateObject.DecrementOpenResultCount | INFO | State Object Id 19, Processing Attention.
23-03-23 10:47:47.0488360 pid:94299 tid:27 sqltools Verbose: 0 : eventTID:6525635 SqlConnection.OnInfoMessage | API | Info | Object Id 19, Message 'Changed database context to 'master'.'
23-03-23 10:47:47.0490980 pid:94299 tid:31 sqltools Verbose: 0 : Done with binding operation for SERVERNAME/Databases/DATABASENAME/Tables
23-03-23 10:47:47.0492880 pid:94299 tid:12 sqltools Verbose: 0 : OE expand canceled
```

**Comment by FredMSJ** [comment]
I removed the https:// from the external adress of my db and it was fixed. 
In case it help some of you.
