### ISSUE TITLE
SQL Migration is not compatible with Azure Government subscription

### ISSUE THREAD

**Issue by kasarava** [microsoft/azuredatastudio#22011]
Issue Type: <b>Bug</b>

 I have added the Azure goverment account in Azure SQL Target configuration step  but it's not listing the subscriptions.  This is causing our migration on hold. Please advise. I am using the ADS version 1.41.2 .

Extension version: 1.3.0
Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cheenamalhotra** [comment]
Hi @kasarava 

Can you confirm you're able to see subscriptions in the Connections > Azure pane and they're not filtered out?

<img src="https://user-images.githubusercontent.com/13396919/221001956-778efc57-077a-498e-8930-5f36d8dfda1e.png" width=500 />

**Comment by cheenamalhotra** [comment]
Closing as resolved with latest v1.41.2, verified internally with @kasarava

**Comment by mchangus** [comment]
Hi @cheenamalhotra!

This is still an issue. After connecting with my azure gov account and Azure pane show three subscriptions, in the wizard for the Azure migration, the subscription dropdown is empty. 

![image](https://github.com/microsoft/azuredatastudio/assets/11968627/7e018142-5388-4a50-ada0-0b05980a8624)

![image](https://github.com/microsoft/azuredatastudio/assets/11968627/1067c0b3-1808-4ac4-ac12-42b59999a773)

Environment Specifications:
Version: 1.43.0 (user setup)
Commit: b790d700898b1095d83e62f0de14678a58222520
Date: 2023-04-10T23:14:27.236Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044

Azure SQL Migration Version: v1.4.4

Thanks,
Mario
