### ISSUE TITLE
ADS won't prompt for AAD token refresh

### ISSUE THREAD

**Issue by automatrio** [microsoft/azuredatastudio#22844]
Issue Type: <b>Bug</b>

1. Try to connect to an Azure DB after a day or so.
2. Connection fails because the token's expired, and ADS won't prompt for authentication.
3. Try removing your account, deleting cached files, and readding the account.
4. Bug persists.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|19.35GB (9.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by automatrio** [comment]
Here's the message it shows when trying to connect:
```
Error: invalid_grant occurred when acquiring token.
70043 - [2023-04-25 15:30:02Z]: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2023-04-24T13:08:30.4547048Z and the maximum allowed lifetime for this request is 43200.
Trace ID: ac510afd-63b2-45d6-8f2e-d471d68b1c00
Correlation ID: 99eba989-e3a6-49e4-9bf7-6618ded7d232
Timestamp: 2023-04-25 15:30:02Z - Correlation ID: 99eba989-e3a6-49e4-9bf7-6618ded7d232 - Trace ID: ac510afd-63b2-45d6-8f2e-d471d68b1c00
```

The issue isn't some much that the token has expired, which is fine, but that ADS won't prompt me to refresh it.
I've also tried closing ADS after deleting my account and before clearing the cache files, but the error persists after reloading it.

In previous versions, it just prompted me to re-authenticate and would connect just fine.

**Comment by automatrio** [comment]
I've checked, and it's not. Would you like to see my settings.json file in its entirety? It's probably very vanilla-ish, since I haven't customized my ADS besides choosing a color theme.

**Comment by cheenamalhotra** [comment]
Hi @automatrio 

Please try below steps once again and capture 'Verbose' logging with MSAL and upload logs here for investigation:
- Remove account
- Clear account token cache
- Add account again

**Comment by automatrio** [comment]
[ads-log_20230428T075539.zip](https://github.com/microsoft/azuredatastudio/files/11352792/ads-log_20230428T075539.zip)

There you go. I've gone through the logs, but there doesn't seem to be anything special.

**Comment by automatrio** [comment]
I've found out that, if I delete my account, add it back, but instead of using the cached account, I choose to "log in with a different organization" (even though it's the same), then it won't use any cached values and will prompt me to perform a full auth again, which then resolves the issue.
Curiously, when I do this, then ADS has me auth'ing twice, and only at the second time does it display that message saying my tenant requires me to re-authenticate.

**Comment by cheenamalhotra** [comment]
We've addressed the re-auth issue with PR https://github.com/microsoft/azuredatastudio/pull/22853 so you'll be prompted to re-authenticate if the error happens again. For the second authentication, please review your tenant configuration with your account, and if it's a personal tenant, their tokens won't long live as much as org tenants.

**Comment by DanielHadad94** [comment]
This error is back on version 1.51.1, and even if you migrate to VSCode, it'll happen there as well.
