### ISSUE TITLE
The Mongo Shell loops in the installation 

### ISSUE THREAD

**Issue by DavideDelVecchio** [microsoft/azuredatastudio#23373]
Type: <b>Bug</b>

I've updated to the newest version of ADS . I just connected to a Mongo cluster by using the provided Mongo settings . When I click on Open Mongo Shell the system is looping on Downloading the MongoShell see the log
 

Installing MongoShell to \.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.3.3\local-resources\v0.3.0\mongoshell\Windows
Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Done installing MongoShell
Installing MongoShell to \.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.3.3\local-resources\v0.3.0\mongoshell\Windows
Done installing MongoShell
Installing MongoShell to \.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.3.3\local-resources\v0.3.0\mongoshell\Windows
Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.60GB (13.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
arc|Mic|1.8.0
azcli|Mic|1.8.0
azure-cosmosdb-ads-extension|Mic|0.3.3
azuredatastudio-dma-oracle|Mic|4.1.2
azuredatastudio-oracle|Mic|0.1.3
azuredatastudio-postgresql|Mic|0.3.1
dacpac|Mic|1.13.0
import|Mic|1.5.5
net-6-runtime|Mic|1.1.0
profiler|Mic|0.12.2
schema-compare|Mic|1.19.0
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|1.1.1

</details>

**Comment by alanrenmsft** [comment]
@languy I don't see the cosmosdb extension repo in my transfer issue target, could you please give me access to your repo so that I can transfer issues in the future?

**Comment by languy** [comment]
> @languy I don't see the cosmosdb extension repo in my transfer issue target, could you please give me access to your repo so that I can transfer issues in the future?

Done.

**Comment by alanrenmsft** [comment]
@languy I still don't see it, could you please do the transfer?

**Comment by Charles-Gagnon** [comment]
@alanrenmsft That's because it's in a different Org

`Note: You can only transfer issues between repositories owned by the same user or organization account. A private repository issue cannot be transferred to a public repository.`

@DavideDelVecchio I'm going to close this one, please reopen an issue in https://github.com/Azure/azure-cosmosdb-ads-extension so the owners can look at it there.

**Comment by DavideDelVecchio** [comment]
@Charles-Gagnon  done! https://github.com/Azure/azure-cosmosdb-ads-extension/issues/87
