### ISSUE TITLE
Import Flat File Wizard Fails on Single Column File

### ISSUE THREAD

**Issue by saefsky** [microsoft/azuredatastudio#3000]
When I try to import a csv with only a single column of data, the "Import flat file wizard" hangs interminably at the "Preview Data" screen. Adding a second column to the file allowed me to continue the process. 

![screen shot 2018-10-24 at 2 12 18 pm](https://user-images.githubusercontent.com/29309414/47451947-09d83d00-d797-11e8-9950-e12c2548b515.png)

- Azure Data Studio Version: 1.0.0 (OS X 10.13.6) and 1.1.3 (OS X 10.14)

Steps to Reproduce:

1. Launch "Import flat file wizard"
2. Select a csv with only a single column
3. Click "next"

**Comment by rdaniels6813** [comment]
This is a due to Microsoft.SqlServer.Prose.ImportBcpTextSynthesis.LearnWithProse() being unable to identify the delimiter for the file and returning an error.  I am pretty sure this library isn't open source, so no easy way to work around this until a fix is made available there.  The difficulty arises from the fact that the remainder of the BCP operations for importing rely on the first one succeeding.

**Comment by yualan** [comment]
I will check with the team, but there should be a fix when we next update PROSE in the import wizard. Will follow-up

**Comment by yualan** [comment]
We have a fix for this issue on the back-end, committer will need to pick up this update.

**Comment by chlafreniere** [comment]
@aaomidi has this since been fixed?

**Comment by aaomidi** [comment]
This issue is fixed.

**Comment by cchowgule** [comment]
I am still experiencing this issue. My csv had 1 col but I added a dummy second col and it still will not get past Preview Data.

"About Azure Data Studio"
Version: 1.14.1 (user setup)
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:42:26.303Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by aaomidi** [comment]
If your CSV doesn't contain sensitive data, could you share it with me? Or create one that fails and share that?

**Comment by cchowgule** [comment]
Attached is 2 CSVs, test.csv with 1 col and test2.csv with 2 cols. Both stick at Preview Data. They both have the same number of rows as the original CSV I was trying to import. I made that CSV by copying a column in an existing spreadsheet and pasting only the values in a new spreadsheet so I don't think there should be any formatting specific issues with the original.

If it helps here is some more details.

The server I am connected to:
Version: 10.50.4042.0
Edition: Express Edition with Advanced Services
OS Version: Windows NT 6.2 <X64> (Build:9200: ) (WOW64)

Excel used to export the CSVs:
Microsoft Excel 2019 MSO (16.0.10325.20024) 32-bit

Azure Data Studio:
Version: 1.14.1 (user setup)
Commit: f9b968c
Date: 2019-12-24T02:42:26.303Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

[testCSVs.zip](https://github.com/microsoft/azuredatastudio/files/4067300/testCSVs.zip)

**Comment by cchowgule** [comment]
.......... I am very sorry. I had the spreadsheet open while I was trying to import it. Both 1 col and 2 col versions work as long as I close the spreadsheet first......

This can now be closed as I am at fault.

**Comment by aaomidi** [comment]
I saw that on my side too. I think this is a valid issue as the UX should tell the user what's going on.

Thanks for reporting this!

**Comment by aaomidi** [comment]
I'll create another issue about this.

**Comment by cchowgule** [comment]
Even if it does not tell the user the specific issue it might be good if the Preview Data screen timed out at some point as I imagine if the csv is really large it may be unclear if the delay is due to the file size or some error.
