### ISSUE TITLE
AzureCore extension tests failing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6429]
https://github.com/microsoft/azuredatastudio/blob/master/extensions/azurecore/src/test/azureResource/tree/treeProvider.test.ts#L113

https://github.com/microsoft/azuredatastudio/blob/master/extensions/azurecore/src/test/azureResource/tree/treeProvider.test.ts#L78

Probably related to #5761

**Comment by Charles-Gagnon** [comment]
@kevcunnane Could you look into these? I think they're because of your changes in #5761

**Comment by abist** [comment]
@Charles-Gagnon  This is most likely due to this - https://github.com/microsoft/azuredatastudio/issues/6413

**Comment by kevcunnane** [comment]
@anthonydresser / @abist can you verify this is fixed by Anthony's recent change? I'll take a look if it really is due to my changes but seems like the layering issue, so appreciate the help given I'm busy on other stuff for the next few days.

**Comment by Charles-Gagnon** [comment]
Tests are still failing after Anthony's fix.

```
MockException: expected invocation of Function() exactly 1 times, invoked 0 times
```

both when checking 

```
mockAccountService.verify((o) => o.getAccounts(), TypeMoq.Times.once());
```

Kevin's change was around modifying how the accounts are loaded which is why I'm thinking that broke these (haven't gone back and verified that myself though)

**Comment by anthonydresser** [comment]
Not sure why I would own this, unless I'm wrong, @Charles-Gagnon , we don't know how long these have been failing, since we haven't run them in the pipelines. Charles added these to the pipeline in his recent PR which is where we see it failing. It's possible it was caused by the recent vscode merge. its also possible it have been failing for a while now.

**Comment by Charles-Gagnon** [comment]
I disabled the tests in the pipeline so they shouldn't be failing the build. This isn't a P0 or anything - just making an issue so we fix them eventually.
