### ISSUE TITLE
Notebooks: Prompt the user when links are disabled

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#8502]
Issue Type: <b>Bug</b>

Links in Notebooks do not work, until you click the "Trusted" button on top. This is un-intuitive. When the user clicks a link, we should atleast show a message to the user that the link will not work because of the Untrusted state, and give an option to Trust the notebook right there in the dialog.

Azure Data Studio version: azuredatastudio 1.13.0 (05a53af085861999ed8dc99596cd55829387d490, 2019-10-22T07:41:49.347Z)
OS version: Windows_NT x64 10.0.18362

**Comment by anthonydresser** [comment]
Did you just create the ADSLivesite label? We should match the standard we have with labels. `Area - Live Site`

**Comment by qifahs** [comment]
Fixed.

**Comment by chlafreniere** [comment]
@qifahs @MsSQLGirl is this something that our livesite users are still encountering, or has the work to trust a workspace/folder been sufficient here?
