### ISSUE TITLE
Azure pane authentication problems

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#8824]
This fixed my SignIn Problems (even with different Tenants), i can now work on the Azure Databases. 

But if I i right click on Database to Manage in the Azure Pane, then i can not connect because the connection will not be pre configured with the right Authentication Values. I have to select Azure AD MFA as Authentication, then it works.

_Originally posted by @DerAlbertCom in https://github.com/microsoft/azuredatastudio/issues/7619#issuecomment-570784737_

We need to opportunistically try to use AAD with Azure Pane, and if that doesn't work silently fallback to SqlLogin for users.

**Comment by aaomidi** [comment]
Fixed :)

**Comment by DerAlbertCom** [comment]
> Fixed :)

Which version?

```
Version: 1.16.1
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:06:16.901Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
stil a problem (freshly updated)

**Comment by DerAlbertCom** [comment]
Nope. Not fixed, I've updated to 1.17

I had to reconnect to Azure (that's may be because of update azure handling, so no bug there).

I can list all the Database and Servers in the Azure Pane, but If I wan't to connect i still have to change Authentication Type and Azure AD Tenant.

If i try direct to Manged a database then I get the login error for user `INSERTSERVERADMINUSERNAME`.

**Comment by aaomidi** [comment]
That's expected behavior at the moment. I'll make an issue with this feature request.

**Comment by aaomidi** [comment]
Unfortunately we had to revert this change at the last minute as it was causing other issues :(

I'll reopen this and start tracking it again.

**Comment by rhythmnewt** [comment]
Any update on this?

**Comment by cheenamalhotra** [comment]
Issue is now fixed as users can choose their default auth type for Azure resources with below setting:

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/816605ea-f10e-40a5-8c63-bb832b62b428" width=500 />
