### ISSUE TITLE
Agent steps don't change status based on current select job run

### ISSUE THREAD

**Issue by Tarig0** [microsoft/azuredatastudio#9152]
- Azure Data Studio Version: 1.15.0
- Azure Agent: 0.45.0

Steps to Reproduce: 

1. Have a job run fail
2. Open the job to view details
3. Select previous run

See steps area not updated

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/sqltoolsservice/pull/922

**Comment by Tarig0** [comment]
Still an issue, job step messages retain the first runs step information

**Comment by Tarig0** [comment]
Please re-open this

**Comment by Charles-Gagnon** [comment]
@Tarig0 This change hasn't made it to ADS yet - I'll get a PR out to update the tools service now after which this should be resolved.

**Comment by Charles-Gagnon** [comment]
@abist Turns out we did actually update the tools service so your fix is in the current insiders release. Please investigate when you get a chance.

**Comment by Tarig0** [comment]
Step messages update status badge next to it does not.

![image](https://user-images.githubusercontent.com/4108180/76093289-b848e080-5f8e-11ea-84b3-f5aba231db68.png)

Version: 1.16.0-insider (user setup)
Commit: 34a7340a18cfb298679ff37dc7297f373e7ffa3f
Date: 2020-03-06T05:55:34.896Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment]
@abist - Please look into that when you get a chance
