### ISSUE TITLE
Latest Insiders doesn't connect using AAD / Separate Tenant

### ISSUE THREAD

**Issue by GoEddie** [microsoft/azuredatastudio#9800]
- Azure Data Studio Version:

Steps to Reproduce:

1. Install latest insiders, create a connection to Azure SQL DB and choose a second separate Azure AD tenant, press connect and the spinner spins forever and this is in the consoel log:

  ERR Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
    at file:///Applications/Azure Data Studio - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1275:789
    at e.fire (file:///Applications/Azure Data Studio - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:197:801)
    at HTMLSelectElement.<anonymous> (file:///Applications/Azure Data Studio - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:496:320)

Insiders Version:

Version: 1.17.0-insider
Commit: b23413d94421319b3e543f65a5adb0dce6027cc6
Date: 2020-03-31T05:47:50.065Z (6 hrs ago)
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by GoEddie** [comment]
I went back to the previous version and this one still  works:

Version: 1.16.0-insider
Commit: 9f9c65591d58c2999a72268e38e176f802fa184d
Date: 2020-03-09T05:48:07.586Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by kburtram** [comment]
@aaomidi do you think this could be related to recent Azure auth changes targeting April release?

**Comment by aaomidi** [comment]
Not related to the azure changes, but the select box changes.

This is fixed by #9811 

@GoEddie could you please confirm you're not seeing this in the latest insiders?

**Comment by aaomidi** [comment]
I'm going to close this. Please feel free to comment back if this issue still exists.

**Comment by GoEddie** [comment]
Hi,

I tried the version form master but it still doesn't work, I click connect and then the spinner spins and never connects.

Thanks,


ed
